name: Build PyWPS ⚙️

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Linting Suite
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install tox
        run: |
          pip install tox>=4.0
      - name: Run linting suite ⚙️
        run: |
          tox -e lint

  test:
    name: Testing with Python${{ matrix.python-version }}
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tox-env: py38-extra
            python-version: "3.8"
          - tox-env: py39-extra
            python-version: "3.9"
          - tox-env: py310-extra
            python-version: "3.10"
          - tox-env: py311-extra
            python-version: "3.11"
    steps:
    - uses: actions/checkout@v4
    - name: Install packages 📦
      run: |
        sudo apt-get update
        sudo apt-get -y install libnetcdf-dev libhdf5-dev
    - uses: actions/setup-python@v5
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox 📦
      run: pip install "tox>=4.0"
    - name: Run tests with tox ⚙️
      run: tox -e ${{ matrix.tox-env }}
    - name: Run coveralls ⚙️
      if: matrix.python-version == 3.8
      uses: AndreMiras/coveralls-python-action@develop

  docs:
    name: Build docs 🏗️
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Setup Python 3.8
        with:
          python-version: 3.8
      - name: Build documentation 🏗️
        run: |
          pip install -e .[dev]
          cd docs && make html
